[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'dist/js'
    target = 'assets/js/modules/countup'
    include = '*.js'
  [[module.mounts]]
    source = 'dist/css/countup.scss'
    target = 'assets/scss/countup.scss'

[params.modules.countup]
  integration = "optional"
  state = "async"